### ISSUE TITLE
开源版有用户管理功能？

### ISSUE THREAD

**Issue by RobertoHuang** [wxiaoqi/Spring-Cloud-AG-Admin#17]
你好
     我在Github上clone了你的开源版项目，可是我没发现有与用户相关的管理接口，比如添加用户，查找用户等，但是在你的ReadMe文件中指出开源版是有用户管理功能的，请问这是什么情况呢？

**Comment by yanjianjia** [comment]
有的，在ace-modules/ace-admin/src/main/java/com/github/wxiaoqi/security/admin/rest/userController中

**Comment by RobertoHuang** [comment]
好的 谢谢
