### ISSUE TITLE
the  Client token expired qustion

### ISSUE THREAD

**Issue by ruixiong-kong** [wxiaoqi/Spring-Cloud-AG-Admin#9]
当admin服务  Client token expired（目前设置3600），在gate网关执行ZuulFilter run方法 使用admin服务外部方法出错 。请问使用什么方案解决？ 对feign服务是否考虑不超时设置？
       看到大牛有refresh刷新方法，但还未实现，是后期准备开发的吗？

**Comment by wxiaoqi** [comment]
后续会准备开发的
